```{r more_inputs, warning=FALSE, message=FALSE}
countries <- read.csv(url("https://raw.githubusercontent.com/gunhojung/315_final_project/master/new%20countries%202.csv"))
library(dplyr)
library(ggplot2)
library(shiny)

shinyApp(
  
  ui = fluidPage(
    inputPanel(
  
      radioButtons("which_variable", label = "Which variable?",
                   choices = c("Average Unemployment Rate (%)" = "avg.region.unemployment",
                               "Average GDP (USD)" = "avg.region.GDP",
                               "Average Population Density" = "avg.region.pop.density"))
    ),
    
    plotOutput("makeup_plot")
  ),
  
  server = function(input, output) {
    output$makeup_plot <- renderPlot({
      
      p <- ggplot(countries) + geom_bar(aes_string(x = "Region", fill = input$which_variable)) + 
  labs(title = "Count of Countries per World Region",
       fill = "") +
  coord_flip() + 
  scale_fill_gradient(low = "orangered3", high = "gold") +
  theme(axis.title = element_text(size = 14), 
        axis.text = element_text(size = 14), 
        axis.text.y = element_text(hjust = 0, vjust = 1),
        title = element_text(size = 18))
      
      p
      
    })
  },
  
  options = list(height = 650)
)
```




```{r more_inputs, warning=FALSE, message=FALSE}
countries <- read.csv(url("https://raw.githubusercontent.com/gunhojung/315_final_project/master/new%20countries%202.csv"))
library(dplyr)
library(ggplot2)
library(shiny)
library(plyr)

shinyApp(
  
  ui = fluidPage(
    inputPanel(
     
      checkboxGroupInput("which_region", label = "Which Regions?",
                   choices = c("Asia" = "ASIA",
                               "Baltics" = "BALTICS",
                               "Commonwealth of Independent States" = "CIS",
                               "Eastern Europe" = "EASTERN EUROPE",
                               "Latin America/Caribbean" = "LATIN AMER. & CARIB",
                               "Near East" = "NEAR EAST",
                               "Northern Africa" = "NORTHERN AFRICA",
                               "Northern America" = "NORTHERN AMERICA",
                               "Oceania" = "OCEANIA",
                               "Sub-Saharan Africa" = "SUB-SAHARAN AFRICA",
                               "Western Europe" = "WESTERN EUROPE")),
      sliderInput("bandwidth_adjust", label = "Adjust the Bandwidth",
                  min = 0.1, max = 1, value = 0.8, step = 0.1),
      checkboxInput("show_rug", label = "Display Rug Plot")
      
    ),
    
    plotOutput("gdp_density")
  ),
  
  server = function(input, output) {
    output$gdp_density <- renderPlot({
      
      pp <- ggplot(subset(countries, Region %in% c(input$which_region))) + geom_density(aes(x = GDP....per.capita., fill = Region, color = Region), alpha = 0.25, adjust = input$bandwidth_adjust) +
        labs(title = "Empirical Density of Global GDPs per capita",
             x = "GDP per Capita (USD)",
             y = "Density")

      if(input$show_rug) {
        pp <- pp + geom_rug(aes(x = GDP....per.capita.)) 
      }
      
      pp
      
    })
  },
  
  options = list(height = 650)
)

ggplot(subset(countries, Region %in% c("OCEANIA"))) + geom_density(aes(x = GDP....per.capita., fill = Region, color = Region), alpha = 0.25, adjust = 0.9)

ggplot(countries) + geom_density(aes(x = GDP....per.capita., fill = Region, color = Region), alpha = 0.25)
```